[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  knolleary/PubSubClient@^2.8
  adafruit/Adafruit SHT31 Library@^2.2.2
  milesburton/DallasTemperature@^3.11.0
  paulstoffregen/OneWire@^2.3.8
  bogde/HX711@^0.7.5

build_flags =
  -DCORE_DEBUG_LEVEL=3
